language: php
dist: trusty
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.composer/cache/repo
    - $TMPDIR/phpstan/cache
php:
  - 7.2

env:
  matrix:
    - ANALYZE=legacy_includes
    - ANALYZE=component_namespace
    - ANALYZE=core_namespace
    - ANALYZE=tests
    - ANALYZE=themes
    - ANALYZE=profiles
    - ANALYZE=modules_1
    - ANALYZE=modules_2
    - ANALYZE=modules_3

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

install:
  - composer global require "hirak/prestissimo:^0.3"
  - composer install -n --prefer-dist --no-suggest --optimize-autoloader --apcu-autoloader

script:
  - ./vendor/bin/phpstan analyse --paths-file ./analyze-paths/$ANALYZE

notifications:
  email: false
