version: 2
defaults: &defaults
  docker:
    - image: circleci/php:7.2-cli
  working_directory: ~/repo
install_prestissimo: &install_prestissimo
  name: Hirak
  command: composer global require "hirak/prestissimo:^0.3"
restore_cache: &restore_cache
  keys:
    - composer-{{ checksum "composer.json" }}
    - composer-
save_cache: &save_cache
  paths:
    - ./vendor
    - ~/.composer/cache
  key: composer-{{ checksum "composer.json" }}

commands:
  do_composer:
    steps:
      - restore_cache: *restore_cache
      - run: *install_prestissimo
      - run: composer install -n --prefer-dist
      - save_cache: *save_cache

jobs:
  core_includes:
    <<: *defaults
    steps:
      - checkout
      - do_composer
      - run: ./vendor/bin/phpstan analyse web/core/includes
  core_component:
    <<: *defaults
    steps:
      - checkout
      - do_composer
      - run: ./vendor/bin/phpstan analyse web/core/lib/Drupal/Component
  core_core:
    <<: *defaults
    steps:
      - checkout
      - do_composer
      - run: ./vendor/bin/phpstan analyse web/core/lib/Drupal/Core

workflows:
  version: 2
  phpstan:
    jobs:
      - core_includes
      - core_component
      - core_core
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - develop
    jobs:
      - phpstan